export const appCopy = {
  home: {
    title: "Orange Booth Duo",
    hu: "Két fotó → ti ketten a narancssárga booth-ban.",
    en: "Two photos → you two in the orange booth.",
    mismatchTitle: "Mismatch",
    mismatch: "Pet + gazdi. Ugyanaz a booth.",
    mismatchEn: "Pet + owner. Same booth.",
    moreSoonHu: "Hamarosan több sablon.",
    moreSoonEn: "More templates soon",
    freeBadgeHu: "1× 8s ingyen",
    freeBadgeEn: "1 free 8s",
    cta: "Create",
  },
  upload: {
    hint: "2 frontal photos · zero prompt · 9:16",
    free: "Generate free clip (8s)",
    freeBadgeHu: "1× 8s ingyen",
    freeBadgeEn: "1 free 8s",
    paid: "Unlock full 15s",
    unlockPrice: "$4.99",
  },
  generating: {
    workingHu: "Készül a klipped…",
    workingEn: "Making your clip…",
    mockHu: "Mock előnézet (nincs API kulcs).",
    mockEn: "Mock preview (no API key).",
  },
  preview: {
    freeHu: "Ez a te ingyenes klipped (8s). Hang nélkül — a soundot TikTokon teszed rá.",
    freeEn: "Your free clip (8s). No audio — add the sound on TikTok.",
    paidHu: "Full booth, 15s. Hang nélkül.",
    paidEn: "Full booth, 15s. No audio.",
    unlock: "Unlock $4.99",
    downloadFree: "Download free",
    freeBadgeHu: "1× 8s ingyen",
    freeBadgeEn: "1 free 8s",
  },
  pay: {
    hu: "Full booth, 15s. Egyszeri $4.99.",
    en: "Full booth, 15s. One-time $4.99.",
    cta: "Unlock $4.99",
    freeBadgeHu: "1× 8s ingyen",
    freeBadgeEn: "1 free 8s",
    starter: "Starter",
    creator: "Creator",
    comingSoonHu: "Hamarosan",
    comingSoonEn: "Coming soon",
    noSubHu: "Nincs előfizetés · egy klip $4.99",
    noSubEn: "No subscription · one clip $4.99",
    noStripeNoteHu: "Fizetés hamarosan — most mock unlock.",
    noStripeNoteEn: "Payments soon — mock unlock for now.",
  },
  download: {
    hu: "MP4, hang nélkül. Nyisd a TikTokot → Add sound.",
    en: "MP4, no audio. Open TikTok → Add sound.",
  },
  done: {
    hu: "Megvan. Próbáld Mismatch-csel: pet + gazdi, ugyanaz a booth.",
    en: "Done. Try Mismatch: pet + owner, same booth.",
  },
  limits: {
    freeUsed:
      "Ma már elhasználtad az ingyenes kliped. Unlock a full 15s-hez.",
    freeUsedEn:
      "You've used today's free clip. Unlock for the full 15s.",
  },
  empty: {
    unknownTemplate: "Unknown template.",
    missingPhotos: "Missing photos. Go back to Upload.",
    loading: "Loading…",
  },
} as const;
